### ISSUE TITLE
NoMethodError: undefined method `remaining_quantity' for nil:NilClass

### ISSUE THREAD

**Issue by lllauri** [indrekj/ib_estonia#14]
Flex defineeritud ja andmed imporditud nii nagu kirjas, vajadusel saan probleemse xmli ka saata.

`/Users/laurilaik/maksud/ib_estonia/lib/ib_estonia/trades/symbol_balance.rb:14:in `close': undefined method `remaining_quantity' for nil:NilClass (NoMethodError)

            if @open_trades[0].remaining_quantity <= quantity
                              ^^^^^^^^^^^^^^^^^^^
	from /Users/laurilaik/maksud/ib_estonia/lib/ib_estonia/trades/tax_report.rb:52:in `block in generate_tax_records_for_symbol'
	from /Users/laurilaik/maksud/ib_estonia/lib/ib_estonia/trades/tax_report.rb:50:in `each'
	from /Users/laurilaik/maksud/ib_estonia/lib/ib_estonia/trades/tax_report.rb:50:in `reduce'
	from /Users/laurilaik/maksud/ib_estonia/lib/ib_estonia/trades/tax_report.rb:50:in `generate_tax_records_for_symbol'
	from /Users/laurilaik/maksud/ib_estonia/lib/ib_estonia/trades/tax_report.rb:12:in `block in generate_tax_records'
	from /Users/laurilaik/maksud/ib_estonia/lib/ib_estonia/trades/tax_report.rb:11:in `each'
	from /Users/laurilaik/maksud/ib_estonia/lib/ib_estonia/trades/tax_report.rb:11:in `reduce'
	from /Users/laurilaik/maksud/ib_estonia/lib/ib_estonia/trades/tax_report.rb:11:in `generate_tax_records'
	from /Users/laurilaik/maksud/ib_estonia/lib/ib_estonia/trades/tax_report.rb:17:in `print'
	from ./start_import.rb:49:in `<main>'`

**Comment by indrekj** [comment]
Kas IB konto on tehtud varem kui 2022? Juhul kui on, siis iga aasta kohta tuleb xml genereerida ja siis käivitad näiteks nii: `./start 2020.xml 2021.xml 2022.xml`. See on vajalik, et generaator teaks millal ja mis andmetega positsioon avati enne kui kinni pandi.

Kui ikka probleemne siis võid xmli saata mulle emailile (peaks githubi profiilis nähtav olema). Aga ma enne nädalavahetust uurima ei hakka.

**Comment by lllauri** [comment]
Jah 2021 Jaanuaris loodud. Flex q-d on tehtud 2021, 2022 ja nüüd proovisin ka 2023 (et oleks absoluutselt kõik andmed), ikka sama.
`./start ib-2021.xml ib-2022.xml ib-2023.xml`
`./start_isin_provider` koos TWS-ga olid ka aktiivsed.

Saadan meilile.

**Comment by indrekj** [comment]
Mul jooksis ilma probleemideta. Võib-olla ruby versiooni erinevus või midagi muud. Igatahes praegu pikemalt uurima ei hakka. Saatsin tulemuse sulle emaili peale.
